# Generated by Django 5.2.6 on 2025-12-04 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeepneyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_input.landmark')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_input.jeepneyroute')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.AddField(
            model_name='jeepneyroute',
            name='stops',
            field=models.ManyToManyField(related_name='routes', through='route_input.RouteStop', to='route_input.landmark'),
        ),
    ]
