# Generated by Django 5.2.6 on 2025-12-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_input', '0002_jeepneyroute_landmark_routestop_jeepneyroute_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='transport_type',
            field=models.CharField(choices=[('Jeepney', 'Jeepney'), ('Taxi', 'Taxi'), ('Motorcycle', 'Motorcycle')], default='Jeepney', max_length=50),
        ),
    ]
