# Generated by Django 5.2.6 on 2025-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_input', '0003_alter_route_transport_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('Jeepney', 'Jeepney'), ('Taxi', 'Taxi'), ('Motorcycle', 'Motorcycle')], max_length=50, unique=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('initial_distance_km', models.DecimalField(decimal_places=2, default=0, help_text='Distance covered by the base fare (e.g., 4km for Jeep)', max_digits=5)),
                ('extra_km_rate', models.DecimalField(decimal_places=2, default=0, help_text='Cost per km after the initial distance', max_digits=5)),
                ('waiting_time_rate_per_min', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='For Taxis only', max_digits=5, null=True)),
                ('long_distance_threshold_km', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Distance where the rate changes (e.g., 8km for Habal-habal)', max_digits=5, null=True)),
                ('long_distance_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cost per km after the long distance threshold', max_digits=5, null=True)),
            ],
        ),
    ]
